adding subscribe to events
Yoctol/react-messenger-send-to-messenger pull request #6
Opened 2018-08-15 11:49 UTC by gijo-varghese

Added a `subcribeEvents` prop which will receive a function. Events from the STM button will be sent to that function. 

e.g.:
```js
  eventListener = e => {
    console.log(e);
  };
  render() {
    return (
      <div>
        <MessengerSendToMessenger
          appId="893463920822463"
          ctaText={this.props.ctaText}
          pageId={this.props.pageId}
          size="xlarge"
          subscribeEvents={this.eventListener}
        />
      </div>
    );
  }
```

2018-08-15 15:10 UTC, chentsulin requested changes

2018-08-15 15:10 UTC, chentsulin commented on src/MessengerSendToMessenger.js
> +    subscribeEvents: PropTypes.func,
I prefer to name it `onSendToMessenger`.

2018-08-15 15:10 UTC, chentsulin commented on src/MessengerSendToMessenger.js
> +    subscribeEvents: () => true,
```js
onSendToMessenger: () => {},
```

2018-08-15 15:10 UTC, chentsulin commented on src/MessengerSendToMessenger.js
> +      window.FB.Event.subscribe('send_to_messenger', e => {
```js
window.FB.Event.subscribe('send_to_messenger', event => {
  if (onSendToMessenger) onSendToMessenger(evemt);
});
```

2018-08-15 16:25 UTC, gijo-varghese commented
Ok. I'll update soon

2018-08-16 03:30 UTC, gijo-varghese commented
I'll create another pull request

2018-08-16 03:30 UTC, closed without merging